Repository ebradley12/Band-Camp-Tracker, pull requests merged in 2024-12, with the labels that each got.

#22 Project overview README.md first draft
  .github/workflows/quality_check.yml
  README.md
  requirements.txt
Labels: documentation

#21 Extraction of sales data from API added
  pipeline/extract.py
  pipeline/test_extract.py
Labels: pipeline

#24 Architecture diagram
  .DS_Store
  docs/.DS_Store
  docs/arch_diagram_mk3.png
  test_push_to_main.py
Labels: documentation, Diagrams

#45 updated architecture diagram
  .DS_Store
  .gitignore
  docs/.DS_Store
  docs/architecture-diagram.png
Labels: documentation, enhancement, System Design

#47 RDS Terraform completed
  .gitignore
  terraform/provider.tf
  terraform/rds.tf
  terraform/variables.tf
Labels: database

#44 Dashboard
  README.md
  dashboard/dashboard_plan.md
  dashboard/wireframe-design.png
Labels: System Design

#49 streamlit dashboard layout complete with email regexing
  dashboard/dashboard.py
  requirements.txt
Labels: enhancement, dashboard

#32 Finished the initial transform script.
  .gitignore
  pipeline/MUSIC_DATA.csv
  pipeline/extract.py
  pipeline/transform.py
  requirements.txt
Labels: pipeline

#51 terraform complete for s3 bucket, tested using boto3
  docs/.DS_Store
  requirements.txt
  terraform/s3.tf
Labels: enhancement, database, Infrastructure

#54 Delete .DS_Store
  .DS_Store
Labels: fix

#53 #17 Pipeline Scheduler Terraform
  terraform/pipeline.tf
  terraform/rds.tf
  terraform/variables.tf
Labels: Infrastructure, Scheduling

#63 dropped table release_genre in schema
  schema.sql
Labels: enhancement, fix

#62 Adding terraform for the ECS for the pipeline
  terraform/pipeline.tf
Labels: documentation, Infrastructure

#61 60 update erd diagram
  docs/erd.png
Labels: documentation, Diagrams

#64 Add Report Generation and Scheduling with Terraform
  terraform/pipeline.tf
  terraform/report.tf
  terraform/s3.tf
  terraform/variables.tf
Labels: Infrastructure

#66 added subscriber information to database
  dashboard/dashboard.py
  dashboard/requirements.txt
  requirements.txt
Labels: database, dashboard

#67 Finished Load Script for the database
  .gitignore
  pipeline/MUSIC_DATA.csv
  pipeline/load.py
  pipeline/transform.py
Labels: pipeline

#70 11 create an entity relationship diagram erd for the database
  docs/erd.png
Labels: documentation, Diagrams

#71 Refactored the load script.
  pipeline/load.py
  pipeline/transform.py
Labels: pipeline

#46 transform.py and load.py tests
  pipeline/extract.py
  pipeline/test_etl.py
  pipeline/test_transform.py
Labels: documentation, pipeline, Testing

#87 ETL pipeline dockerised and Lambda created
  dashboard/dashboard.py
  docker/pipeline_dockerfile
  pipeline/Dockerfile
  pipeline/etl.py
  pipeline/extract.py
  pipeline/requirements.txt
  pipeline/transform.py
  schema.sql
  terraform/ecr/ecr.tf
  terraform/pipeline/pipeline.tf
Labels: enhancement, pipeline, fix, Infrastructure, docker

#91 Erd update
  docs/erd.png
Labels: documentation, Diagrams

#84 Updated Main README.md and pipeline README.md
  README.md
  pipeline/README.md
Labels: documentation

#81 Implemented a README.md for the report folder
  reports/README.md
Labels: documentation

#85 Report Generation Docker & Streamlit Docker
  docker/report_generation_dockerfile
  docker/streamlit_dockerfile
Labels: pipeline, docker

#103 updated subscribe page with login portal
  dashboard/dashboard.py
  dashboard/subscribe_page_commands.py
Labels: enhancement, dashboard

#101 Create ECR Repositories for Dashboard, Alerts, and Reports; Update Reports Files and Terraform for Email Sending and Scheduling
  .gitignore
  dashboard/Dockerfile
  docker/report_generation_dockerfile
  reports/Dockerfile
  reports/daily_sales_report_2024-12-05.pdf
  reports/emailer.py
  reports/graphs.py
  reports/lambda_handler.py
  reports/report_generator.py
  reports/requirements.txt
  terraform/ecr/alerts.tf
  terraform/ecr/dashboard.tf
  terraform/ecr/pipeline.tf
  terraform/ecr/reports.tf
  terraform/rds/rds.tf
  terraform/reports/report.tf
  terraform/variables.tf
Labels: enhancement, Infrastructure, terraform

#75 Finished chart for top genre sales
  dashboard/dashboard.py
  dashboard/streamlit_graphs/__init__.py
  dashboard/streamlit_graphs/release_type_chart.py
  dashboard/streamlit_graphs/sales_by_country.py
  dashboard/streamlit_graphs/sales_over_time.py
  dashboard/streamlit_graphs/top_artist_sales.py
  dashboard/streamlit_graphs/top_genre_sales.py
Labels: dashboard

#99 Dashboard Terraform
  terraform/dashboard/dashboard.tf
  terraform/dashboard/provider.tf
  terraform/dashboard/variables.tf
Labels: dashboard, terraform

#109 Adding top artists to genre alerts
  alerts/alerts.py
  alerts/queries.py
Labels: alerts

#104 updated architecture diagram with changes made in resources and design
  docs/.DS_Store
  docs/architecture-diagram.png
Labels: documentation, enhancement, Diagrams, fix

#108 Add Lambda Handler Function and Dockerfile for Alerts Service
  alerts/Dockerfile
  alerts/lambda_handler.py
  reports/lambda_handler.py
  reports/queries.py
Labels: Infrastructure

#112 Dashboard reports page
  .gitignore
  dashboard/dashboard.py
  docs/.DS_Store
Labels: enhancement, dashboard

#93 README.md for Terraform File
  terraform/README.md
Labels: documentation

#116 #94 Creating all the Alerts infrastructure Terraform
  terraform/alerts/alerts.tf
  terraform/alerts/variables.tf
  terraform/pipeline/variables.tf
  terraform/rds/variables.tf
  terraform/reports/variables.tf
Labels: Infrastructure, terraform

#119 added graphs to dashboard and fixed filter for sales over time
  dashboard/dashboard.py
  dashboard/streamlit_graphs/release_type_chart.py
  dashboard/streamlit_graphs/sales_over_time.py
Labels: fix, dashboard

#120 Reports update
  reports/queries.py
  terraform/reports/report.tf
Labels: fix

#123 Embeddings are able to be shown on the dashboard
  dashboard/embeddings.py
Labels: dashboard

#122 Draft Alerts `README.md`
  alerts/README.md
Labels: documentation

#127 cloud hosting dashboard
  dashboard/Dockerfile
  dashboard/requirements.txt
  terraform/dashboard/dashboard.tf
  terraform/dashboard/variables.tf
Labels: dashboard, docker, terraform

#131 Enhance Dashboard Navigation and Filtering
  dashboard/streamlit_graphs/queries.py
  dashboard/streamlit_graphs/release_type_chart.py
  dashboard/streamlit_graphs/sales_by_country.py
  dashboard/streamlit_graphs/sales_over_time.py
  dashboard/streamlit_graphs/top_artist_sales.py
  dashboard/streamlit_graphs/top_genre_sales.py
Labels: enhancement

#134 Created logo for BandScout
  .gitignore
  docs/BandScout_logo.png
Labels: enhancement, Diagrams, dashboard

#135 small changes to logo
  docs/BandScout_logo.png
Labels: enhancement, Diagrams, dashboard

#128 Dashboard README.md
  dashboard/README.md
Labels: documentation

#137 124 format the the dashboard
  dashboard/BandScout_logo.png
  dashboard/dashboard.py
  dashboard/dashboard_formatting.py
  dashboard/streamlit_graphs/release_type_chart.py
  dashboard/streamlit_graphs/sales_by_country.py
  dashboard/streamlit_graphs/sales_over_time.py
  dashboard/streamlit_graphs/top_artist_sales.py
  dashboard/streamlit_graphs/top_genre_sales.py
Labels: enhancement, dashboard

#138 Quality Checking
  alerts/alerts.py
  alerts/lambda_handler.py
  dashboard/dashboard.py
  dashboard/streamlit_graphs/queries.py
  dashboard/streamlit_graphs/sales_by_country.py
  dashboard/streamlit_graphs/sales_over_time.py
  dashboard/streamlit_graphs/top_artist_sales.py
  dashboard/streamlit_graphs/top_genre_sales.py
Labels: documentation

#140 Some tests for the alert script
  alerts/test_alerts.py
Labels: Testing, alerts

#144 Updated dash cloud hosted
  dashboard/BandScout_logo.png
  dashboard/Dockerfile
  dashboard/dashboard.py
  dashboard/embeddings.py
  dashboard/requirements.txt
  dashboard/streamlit_graphs/sales_over_time.py
  pipeline/extract.py
  terraform/dashboard/dashboard.tf
Labels: enhancement, dashboard, docker

#147 Finished adding tests for report generation
  reports/report_generator.py
  reports/test_report_generator.py
Labels: Testing

#148 fixes to various READMEs
  README.md
  alerts/README.md
  dashboard/README.md
  reports/README.md
Labels: documentation, fix
